### ISSUE TITLE
Uint64Range broken with go 1.9.2

### ISSUE THREAD

**Issue by plinss** [averagesecurityguy/random#2]
When using this code on go 1.9.2 on macOS, Uint64Range always returns 0.

On line 29, `val, err := Uint64()` is apparently shadowing val within the for loop and the outer `val` var is never getting assigned. (No warnings during build.) I'm not sure if this behavior changed in recent version of go.

**Comment by averagesecurityguy** [comment]
Fixed. Sorry I didn't see this until now. Github is not informing me when issues are raised.
37cce341d2aff89f9c6f6bcf85e6b5b6d66f5649
